### ISSUE TITLE
Peer review of the ReversiAI game code

### ISSUE THREAD

**Issue by jpirhel** [LittleHaku/ReversiAI#2]
source code cloned: 13.10.2023 at about 17:00

newest commit at the time of cloning:

Thu Oct 12 13:58:14 2023 +0300

These comments are mostly more about the technical quality of the source code rather than the architecture of the prorgram architecture or the quality of the algorithms.

**improvement suggestion 1**

Testing: The logic engine is pretty thoroughly tested, but perhaps a bit more "weird" test cases?

**improvement suggestion 2**

The GUI and the game logic, and also the test cases could be split into several classes, each with only related functionality. Now, all GUI code is in one file, all logic code is in one file, and all test cases are in one file. This doesn't seem like a good approach, as the program grows in complexity.

**improvement suggestion 3**

There seems to be some "magic numbers" in the code. For example: 

```
    def handle_click(self, event):
        col = event.x // 50
        row = event.y // 50

```

Where does this number 50 come from? What does it represent? Pixel values or something else? Renaming it to PIXELS_PER_SQUARE (or some such) could improve readability of the code.

**improvement suggestion 4**

The code seems to be pretty procedural. The GUI could perhaps better be implemented as an event-driven architecture, simplifying the code.

**General comments about the code**

The code seems nicely formatted and is pretty idiomatic Python. 

**General comments about the GUI**

The GUI seems quite OK. The game is playable, and this tester lost to the AI by quite a margin. It would be nice if the game board would get larger as one increased the window size. At the moment the window is resizable but resizing the window only adds margins outside the board.

**General comments about testing (test cases)**

The logic engine seems pretty thoroughly tested, and I especially liked that the test cases source code did include quite a lot of inline comments.

**General comments about game logic**

The logic seems to be quite sound. I would have liked more inline comments explaining what the code does. Otherwise, good job!

**Comment by LittleHaku** [comment]
Thank you for the feedback:)
